//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("polendamusModel", "FK_Nivel_Planta", "Alergias", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Polendamus.Alergias), "Niveles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Polendamus.Niveles), true)]
[assembly: EdmRelationshipAttribute("polendamusModel", "FK_Nivel_Provincia", "Provincias", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Polendamus.Provincias), "Niveles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Polendamus.Niveles), true)]
[assembly: EdmRelationshipAttribute("polendamusModel", "FK_Predicciones_Provincia", "Provincias", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Polendamus.Provincias), "Predicciones", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Polendamus.Predicciones), true)]
[assembly: EdmRelationshipAttribute("polendamusModel", "FK_URL_Provincia", "Provincias", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Polendamus.Provincias), "UrlsTiempo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Polendamus.UrlsTiempo), true)]

#endregion

namespace Polendamus
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class polendamusEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new polendamusEntities object using the connection string found in the 'polendamusEntities' section of the application configuration file.
        /// </summary>
        public polendamusEntities() : base("name=polendamusEntities", "polendamusEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new polendamusEntities object.
        /// </summary>
        public polendamusEntities(string connectionString) : base(connectionString, "polendamusEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new polendamusEntities object.
        /// </summary>
        public polendamusEntities(EntityConnection connection) : base(connection, "polendamusEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Alergias> Alergias
        {
            get
            {
                if ((_Alergias == null))
                {
                    _Alergias = base.CreateObjectSet<Alergias>("Alergias");
                }
                return _Alergias;
            }
        }
        private ObjectSet<Alergias> _Alergias;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Niveles> Niveles
        {
            get
            {
                if ((_Niveles == null))
                {
                    _Niveles = base.CreateObjectSet<Niveles>("Niveles");
                }
                return _Niveles;
            }
        }
        private ObjectSet<Niveles> _Niveles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Predicciones> Predicciones
        {
            get
            {
                if ((_Predicciones == null))
                {
                    _Predicciones = base.CreateObjectSet<Predicciones>("Predicciones");
                }
                return _Predicciones;
            }
        }
        private ObjectSet<Predicciones> _Predicciones;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Provincias> Provincias
        {
            get
            {
                if ((_Provincias == null))
                {
                    _Provincias = base.CreateObjectSet<Provincias>("Provincias");
                }
                return _Provincias;
            }
        }
        private ObjectSet<Provincias> _Provincias;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UrlsTiempo> UrlsTiempo
        {
            get
            {
                if ((_UrlsTiempo == null))
                {
                    _UrlsTiempo = base.CreateObjectSet<UrlsTiempo>("UrlsTiempo");
                }
                return _UrlsTiempo;
            }
        }
        private ObjectSet<UrlsTiempo> _UrlsTiempo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bocadillos> Bocadillos
        {
            get
            {
                if ((_Bocadillos == null))
                {
                    _Bocadillos = base.CreateObjectSet<Bocadillos>("Bocadillos");
                }
                return _Bocadillos;
            }
        }
        private ObjectSet<Bocadillos> _Bocadillos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Dibujos> Dibujos
        {
            get
            {
                if ((_Dibujos == null))
                {
                    _Dibujos = base.CreateObjectSet<Dibujos>("Dibujos");
                }
                return _Dibujos;
            }
        }
        private ObjectSet<Dibujos> _Dibujos;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Alergias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAlergias(Alergias alergias)
        {
            base.AddObject("Alergias", alergias);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Niveles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNiveles(Niveles niveles)
        {
            base.AddObject("Niveles", niveles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Predicciones EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPredicciones(Predicciones predicciones)
        {
            base.AddObject("Predicciones", predicciones);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Provincias EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProvincias(Provincias provincias)
        {
            base.AddObject("Provincias", provincias);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UrlsTiempo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUrlsTiempo(UrlsTiempo urlsTiempo)
        {
            base.AddObject("UrlsTiempo", urlsTiempo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bocadillos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBocadillos(Bocadillos bocadillos)
        {
            base.AddObject("Bocadillos", bocadillos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Dibujos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDibujos(Dibujos dibujos)
        {
            base.AddObject("Dibujos", dibujos);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="polendamusModel", Name="Alergias")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Alergias : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Alergias object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        public static Alergias CreateAlergias(global::System.Int32 id, global::System.String nombre)
        {
            Alergias alergias = new Alergias();
            alergias.Id = id;
            alergias.Nombre = nombre;
            return alergias;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EsArbol
        {
            get
            {
                return _EsArbol;
            }
            set
            {
                OnEsArbolChanging(value);
                ReportPropertyChanging("EsArbol");
                _EsArbol = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EsArbol");
                OnEsArbolChanged();
            }
        }
        private Nullable<global::System.Boolean> _EsArbol;
        partial void OnEsArbolChanging(Nullable<global::System.Boolean> value);
        partial void OnEsArbolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Visible;
        partial void OnVisibleChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("polendamusModel", "FK_Nivel_Planta", "Niveles")]
        public EntityCollection<Niveles> Niveles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Niveles>("polendamusModel.FK_Nivel_Planta", "Niveles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Niveles>("polendamusModel.FK_Nivel_Planta", "Niveles", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="polendamusModel", Name="Bocadillos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bocadillos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bocadillos object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="texto">Initial value of the Texto property.</param>
        /// <param name="esHoy">Initial value of the EsHoy property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        /// <param name="esGet">Initial value of the EsGet property.</param>
        public static Bocadillos CreateBocadillos(global::System.Int32 id, global::System.String texto, global::System.Boolean esHoy, global::System.String estado, global::System.Boolean esGet)
        {
            Bocadillos bocadillos = new Bocadillos();
            bocadillos.Id = id;
            bocadillos.Texto = texto;
            bocadillos.EsHoy = esHoy;
            bocadillos.Estado = estado;
            bocadillos.EsGet = esGet;
            return bocadillos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Texto
        {
            get
            {
                return _Texto;
            }
            set
            {
                OnTextoChanging(value);
                ReportPropertyChanging("Texto");
                _Texto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Texto");
                OnTextoChanged();
            }
        }
        private global::System.String _Texto;
        partial void OnTextoChanging(global::System.String value);
        partial void OnTextoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EsHoy
        {
            get
            {
                return _EsHoy;
            }
            set
            {
                OnEsHoyChanging(value);
                ReportPropertyChanging("EsHoy");
                _EsHoy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EsHoy");
                OnEsHoyChanged();
            }
        }
        private global::System.Boolean _EsHoy;
        partial void OnEsHoyChanging(global::System.Boolean value);
        partial void OnEsHoyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EsGet
        {
            get
            {
                return _EsGet;
            }
            set
            {
                OnEsGetChanging(value);
                ReportPropertyChanging("EsGet");
                _EsGet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EsGet");
                OnEsGetChanged();
            }
        }
        private global::System.Boolean _EsGet;
        partial void OnEsGetChanging(global::System.Boolean value);
        partial void OnEsGetChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="polendamusModel", Name="Dibujos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Dibujos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Dibujos object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="esHoy">Initial value of the EsHoy property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        public static Dibujos CreateDibujos(global::System.Int32 id, global::System.String nombre, global::System.Boolean esHoy, global::System.String estado)
        {
            Dibujos dibujos = new Dibujos();
            dibujos.Id = id;
            dibujos.Nombre = nombre;
            dibujos.EsHoy = esHoy;
            dibujos.Estado = estado;
            return dibujos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EsHoy
        {
            get
            {
                return _EsHoy;
            }
            set
            {
                OnEsHoyChanging(value);
                ReportPropertyChanging("EsHoy");
                _EsHoy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EsHoy");
                OnEsHoyChanged();
            }
        }
        private global::System.Boolean _EsHoy;
        partial void OnEsHoyChanging(global::System.Boolean value);
        partial void OnEsHoyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="polendamusModel", Name="Niveles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Niveles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Niveles object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="id_Provincia">Initial value of the Id_Provincia property.</param>
        /// <param name="id_Planta">Initial value of the Id_Planta property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        public static Niveles CreateNiveles(global::System.Int32 id, global::System.Int32 id_Provincia, global::System.Int32 id_Planta, global::System.String estado, global::System.String descripcion)
        {
            Niveles niveles = new Niveles();
            niveles.Id = id;
            niveles.Id_Provincia = id_Provincia;
            niveles.Id_Planta = id_Planta;
            niveles.Estado = estado;
            niveles.Descripcion = descripcion;
            return niveles;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Provincia
        {
            get
            {
                return _Id_Provincia;
            }
            set
            {
                OnId_ProvinciaChanging(value);
                ReportPropertyChanging("Id_Provincia");
                _Id_Provincia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Provincia");
                OnId_ProvinciaChanged();
            }
        }
        private global::System.Int32 _Id_Provincia;
        partial void OnId_ProvinciaChanging(global::System.Int32 value);
        partial void OnId_ProvinciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Planta
        {
            get
            {
                return _Id_Planta;
            }
            set
            {
                OnId_PlantaChanging(value);
                ReportPropertyChanging("Id_Planta");
                _Id_Planta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Planta");
                OnId_PlantaChanged();
            }
        }
        private global::System.Int32 _Id_Planta;
        partial void OnId_PlantaChanging(global::System.Int32 value);
        partial void OnId_PlantaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("polendamusModel", "FK_Nivel_Planta", "Alergias")]
        public Alergias Alergias
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alergias>("polendamusModel.FK_Nivel_Planta", "Alergias").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alergias>("polendamusModel.FK_Nivel_Planta", "Alergias").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Alergias> AlergiasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Alergias>("polendamusModel.FK_Nivel_Planta", "Alergias");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Alergias>("polendamusModel.FK_Nivel_Planta", "Alergias", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("polendamusModel", "FK_Nivel_Provincia", "Provincias")]
        public Provincias Provincias
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provincias>("polendamusModel.FK_Nivel_Provincia", "Provincias").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provincias>("polendamusModel.FK_Nivel_Provincia", "Provincias").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Provincias> ProvinciasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provincias>("polendamusModel.FK_Nivel_Provincia", "Provincias");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Provincias>("polendamusModel.FK_Nivel_Provincia", "Provincias", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="polendamusModel", Name="Predicciones")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Predicciones : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Predicciones object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="id_Provincia">Initial value of the Id_Provincia property.</param>
        /// <param name="estado">Initial value of the Estado property.</param>
        public static Predicciones CreatePredicciones(global::System.Int32 id, global::System.Int32 id_Provincia, global::System.String estado)
        {
            Predicciones predicciones = new Predicciones();
            predicciones.Id = id;
            predicciones.Id_Provincia = id_Provincia;
            predicciones.Estado = estado;
            return predicciones;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Provincia
        {
            get
            {
                return _Id_Provincia;
            }
            set
            {
                OnId_ProvinciaChanging(value);
                ReportPropertyChanging("Id_Provincia");
                _Id_Provincia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Provincia");
                OnId_ProvinciaChanged();
            }
        }
        private global::System.Int32 _Id_Provincia;
        partial void OnId_ProvinciaChanging(global::System.Int32 value);
        partial void OnId_ProvinciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("polendamusModel", "FK_Predicciones_Provincia", "Provincias")]
        public Provincias Provincias
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provincias>("polendamusModel.FK_Predicciones_Provincia", "Provincias").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provincias>("polendamusModel.FK_Predicciones_Provincia", "Provincias").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Provincias> ProvinciasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provincias>("polendamusModel.FK_Predicciones_Provincia", "Provincias");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Provincias>("polendamusModel.FK_Predicciones_Provincia", "Provincias", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="polendamusModel", Name="Provincias")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Provincias : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Provincias object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        public static Provincias CreateProvincias(global::System.Int32 id, global::System.String nombre)
        {
            Provincias provincias = new Provincias();
            provincias.Id = id;
            provincias.Nombre = nombre;
            return provincias;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("polendamusModel", "FK_Nivel_Provincia", "Niveles")]
        public EntityCollection<Niveles> Niveles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Niveles>("polendamusModel.FK_Nivel_Provincia", "Niveles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Niveles>("polendamusModel.FK_Nivel_Provincia", "Niveles", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("polendamusModel", "FK_Predicciones_Provincia", "Predicciones")]
        public EntityCollection<Predicciones> Predicciones
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Predicciones>("polendamusModel.FK_Predicciones_Provincia", "Predicciones");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Predicciones>("polendamusModel.FK_Predicciones_Provincia", "Predicciones", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("polendamusModel", "FK_URL_Provincia", "UrlsTiempo")]
        public EntityCollection<UrlsTiempo> UrlsTiempo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UrlsTiempo>("polendamusModel.FK_URL_Provincia", "UrlsTiempo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UrlsTiempo>("polendamusModel.FK_URL_Provincia", "UrlsTiempo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="polendamusModel", Name="UrlsTiempo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UrlsTiempo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UrlsTiempo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="url">Initial value of the url property.</param>
        /// <param name="id_Provincia">Initial value of the Id_Provincia property.</param>
        public static UrlsTiempo CreateUrlsTiempo(global::System.Int32 id, global::System.String url, global::System.Int32 id_Provincia)
        {
            UrlsTiempo urlsTiempo = new UrlsTiempo();
            urlsTiempo.Id = id;
            urlsTiempo.url = url;
            urlsTiempo.Id_Provincia = id_Provincia;
            return urlsTiempo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Provincia
        {
            get
            {
                return _Id_Provincia;
            }
            set
            {
                OnId_ProvinciaChanging(value);
                ReportPropertyChanging("Id_Provincia");
                _Id_Provincia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id_Provincia");
                OnId_ProvinciaChanged();
            }
        }
        private global::System.Int32 _Id_Provincia;
        partial void OnId_ProvinciaChanging(global::System.Int32 value);
        partial void OnId_ProvinciaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("polendamusModel", "FK_URL_Provincia", "Provincias")]
        public Provincias Provincias
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provincias>("polendamusModel.FK_URL_Provincia", "Provincias").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provincias>("polendamusModel.FK_URL_Provincia", "Provincias").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Provincias> ProvinciasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Provincias>("polendamusModel.FK_URL_Provincia", "Provincias");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Provincias>("polendamusModel.FK_URL_Provincia", "Provincias", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
